/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuestionType = IDL.Variant({
  'rating_1_5' : IDL.Null,
  'text' : IDL.Null,
  'multipleChoice' : IDL.Vec(IDL.Text),
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'questionLabel' : IDL.Text,
  'questionType' : QuestionType,
});
export const SurveyForm = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'questions' : IDL.Vec(Question),
});
export const Response = IDL.Record({
  'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
  'respondent' : IDL.Opt(IDL.Principal),
  'formId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createForm' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Nat], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getForm' : IDL.Func([IDL.Nat], [IDL.Opt(SurveyForm)], ['query']),
  'getFormResponses' : IDL.Func([IDL.Nat], [IDL.Vec(Response)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listForms' : IDL.Func([], [IDL.Vec(SurveyForm)], ['query']),
  'submitResponse' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)), IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuestionType = IDL.Variant({
    'rating_1_5' : IDL.Null,
    'text' : IDL.Null,
    'multipleChoice' : IDL.Vec(IDL.Text),
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'questionLabel' : IDL.Text,
    'questionType' : QuestionType,
  });
  const SurveyForm = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'questions' : IDL.Vec(Question),
  });
  const Response = IDL.Record({
    'answers' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)),
    'respondent' : IDL.Opt(IDL.Principal),
    'formId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createForm' : IDL.Func([IDL.Text, IDL.Vec(Question)], [IDL.Nat], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getForm' : IDL.Func([IDL.Nat], [IDL.Opt(SurveyForm)], ['query']),
    'getFormResponses' : IDL.Func([IDL.Nat], [IDL.Vec(Response)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listForms' : IDL.Func([], [IDL.Vec(SurveyForm)], ['query']),
    'submitResponse' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text)), IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };